# Kr atom - basis set tests

In [1]:
import numpy as np
import pandas as pd
import functools

%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

In [29]:
from IPython.display import display,HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
}
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [30]:
HTML("""
<style>
    table.dataframe thead th:first-child {
        display: none;
    }
    table.dataframe tbody th {
        display: none;
    }
</style>
""")

## toc <a name="toc"></a>

* [Even-tempered sets](#et)
    * [Based on dyall.v3z](#et_dyallv3z)
    * [Based on dyall.acv4z](#et_dyallacv4z)    
* [Well-tempered sets](#wt)

In [33]:
def plot_completeness_profiles(df, max_l, title, xrange, save=''):
    
    # set labels:
    labels=["s", "p", "d", "f", "g", "h", "i"]

    # plot
    plt.style.use('seaborn-whitegrid')
    fig = plt.figure()
    fig.set_size_inches(20,10)
    ax = fig.add_subplot(1, 1, 1)

    # settings
    m = ['o','D','v','8','^','*', '>']
    cb = ["darkgreen","red","blue","purple","gold","sienna","pink"]

    if max_l >= 0:
        ax.plot(df["probe"], df["s"], color=cb[0], marker=m[0], linewidth=1, markersize=4)
    if max_l >= 1:    
        ax.plot(df["probe"], df["p"], color=cb[1], marker=m[1], linewidth=1, markersize=4)
    if max_l >= 2:    
        ax.plot(df["probe"], df["d"], color=cb[2], marker=m[2], linewidth=1, markersize=4)
    if max_l >= 3:    
        ax.plot(df["probe"], df["f"], color=cb[3], marker=m[3], linewidth=1, markersize=4)
    if max_l >= 4:    
        ax.plot(df["probe"], df["g"], color=cb[4], marker=m[4], linewidth=1, markersize=4)
    if max_l >= 5:    
        ax.plot(df["probe"], df["h"], color=cb[5], marker=m[5], linewidth=1, markersize=4)  
    if max_l >= 6:    
        ax.plot(df["probe"], df["i"], color=cb[6], marker=m[6], linewidth=1, markersize=4)         
    if max_l >= 7:
        print("add higher exponents")

    # limits, labels, ticks and legend    
    plt.title(title, fontsize=24)
    ax.set_xlabel(r"$log(\alpha)$",fontsize=20)
    ax.set_ylabel(r"Y($\alpha$)", fontsize=20)

    plt.xlim(xrange[0], xrange[1])
    plt.legend(prop={'size':18}, fancybox=True, loc='center left', bbox_to_anchor=(1.0, 0.5), ncol=1, shadow=True)

    if save:
        plt.savefig(save)


def read_energy_into_dataframe(fname):
    df = pd.read_csv(fname,sep=',',skiprows=2, 
                     names=["name","basis_set","total_energy", "Niter"])
    df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
    return df

def calc_Ediff(df,refset):
    Eref  = df.loc[df['name'] == refset]['total_energy'].values
    Ediff  = df['total_energy'] - Eref[0]
    absEdiff  = abs(Ediff)
    df['Ediff'] = Ediff
    df['absEdiff'] = absEdiff
    return df

In [27]:
# all floats in this notebook are displayed with 2 decimal digits
pd.options.display.float_format = '{:.13f}'.format

## Even-tempered sets <a name="et"></a>
[go to TOC](#toc)

### based on dyall.v3z <a name="et_dyallv3z"></a>
[go to TOC](#toc)

In [28]:
data_v3z = read_energy_into_dataframe('results_v3z.csv')
data_v3z=calc_Ediff(data_v3z,'Kr_dyallv3z')

data_v3z.sort_values(by=['absEdiff'],ascending=True,ignore_index=True)

,name,basis_set,total_energy,Niter,Ediff,absEdiff
0,Kr_dyallv3z,23s16p10d1f,-2801.2925148237459,11,0.0000000000000,0.0000000000000
1,Kr_et_3z_start_from_minelement_dyallv3z,28s20p12d1f,-2801.2925154096010,11,-0.0000005858551,0.0000005858551
2,Kr_et_3z_start_from_maxall_dyallv3z,28s20p12d1f,-2801.2924394673528,11,0.0000753563932,0.0000753563932
3,Kr_et_3z_start_from_minall_dyallv3z,28s21p13d1f,-2801.2926953534570,11,-0.0001805297111,0.0001805297111
4,Kr_et_3z_start_from_maxelement_dyallv3z,27s21p12d1f,-2801.2928109450445,11,-0.0002961212986,0.0002961212986
5,Kr_et_4z_start_from_minelement_dyallv3z,37s26p16d1f,-2801.2933431625361,50*,-0.0008283387901,0.0008283387901
6,Kr_et_4z_start_from_maxall_dyallv3z,37s27p15d1f,-2801.2935682724828,50*,-0.0010534487369,0.0010534487369
7,Kr_et_4z_start_from_maxelement_dyallv3z,36s27p16d1f,-2801.2935759429674,50*,-0.0010611192215,0.0010611192215
8,Kr_et_4z_start_from_minall_dyallv3z,36s27p16d1f,-2801.2935866823250,50*,-0.0010718585791,0.0010718585791

### based on dyall.acv4z <a name="et_dyallacv4z"></a>
[go to TOC](#toc)

In [32]:
data_acv4z = read_energy_into_dataframe('results_acv4z.csv')
data_acv4z=calc_Ediff(data_acv4z,'Kr_dyallacv4z')

data_acv4z.sort_values(by=['absEdiff'],ascending=True,ignore_index=True)

,name,basis_set,total_energy,Niter,Ediff,absEdiff
0,Kr_dyallacv4z,31s22p14d6f4g1h,-2801.2936360414110,11,0.0000000000000,0.0000000000000
1,Kr_et_4z_start_from_minall_dyallacv4z,39s35p20d10f8g1h,-2801.2937850564363,50*,-0.0001490150253,0.0001490150253
2,Kr_et_4z_start_from_minelement_dyallacv4z,39s34p20d10f8g1h,-2801.2937999226237,50*,-0.0001638812128,0.0001638812128
3,Kr_et_4z_start_from_maxall_dyallacv4z,39s34p20d10f8g1h,-2801.2938021414693,50*,-0.0001661000583,0.0001661000583
4,Kr_et_4z_start_from_maxelement_dyallacv4z,39s34p20d10f8g1h,-2801.2938029518641,50*,-0.0001669104531,0.0001669104531
5,Kr_et_3z_start_from_maxall_dyallacv4z,30s26p16d8f7g1h,-2801.2929260498254,12,0.0007099915856,0.0007099915856
6,Kr_et_3z_start_from_maxelement_dyallacv4z,29s26p16d8f7g1h,-2801.2928992371412,11,0.0007368042698,0.0007368042698
7,Kr_et_3z_start_from_minall_dyallacv4z,30s27p15d8f6g1h,-2801.2927864788271,23,0.0008495625839,0.0008495625839
8,Kr_et_3z_start_from_minelement_dyallacv4z,30s26p15d8f7g1h,-2801.2926953534570,50*,0.0009406879540,0.0009406879540

* Desired convergence limit not reached after   50 iterations but the current convergence is acceptable

thresholds:
```
.EVCCNV
 1.0D-08 1.0D-6
```